### ISSUE TITLE
issue 1) Controls don’t initialize audio until touched (attack/release/duration inactive on load)

### ISSUE THREAD

**Issue by juliesemoroz** [viniciusfersil123/sponges_sonification#2]
1) Controls don’t initialize audio until touched (attack/release/duration inactive on load)

Summary
When the patch opens (or DSP is toggled on), no sound is produced until the user manually clicks the attack, release, and duration controls on each “sponge.” GUI values appear correct but are not emitted to the DSP graph on load.

Steps to Reproduce

Open the main PD patch.

Ensure DSP is on.

Trigger a sponge without touching its ARD controls.

Observe: no envelope behavior until a control is clicked.

Expected Behavior
On patch open (and when DSP is turned on), each sponge automatically sends its current attack, release, and duration values into the DSP chain so sound behaves correctly without user interaction.

Actual Behavior
GUI widgets display the last-saved values, but those values are not sent to DSP objects until the widgets are manually clicked.

Acceptance Criteria

On patch open, every sponge’s ARD parameters are sent to the DSP chain exactly once.

Toggling DSP off/on also re-sends the parameters (optional but preferred).

No user interaction is required to get correct sound behavior.

Implementation Notes (PD)

GUI objects (hslider, vslider, nbx) do not output their value when set programmatically.

Add [loadbang] (or [initbang] if you need “graph-on-parent” safety) inside each sponge abstraction to:

read the current stored value (e.g., via [f] or [value]), and

send it directly to the DSP inlet and optionally update the GUI.

If presets or state storage use ; sliderX 123( messages, those update visuals only. Pair them with an explicit $1 message to the DSP parameter bus (e.g., [s sponge-1/attack]).

Pattern example:

[loadbang]
   |
  [t b b]
   |   \__________ [bang GUI to reflect current]
   \______________ [send current numeric value to DSP inlet]

Consider a small “Param” abstraction that always mirrors GUI ↔ DSP (visual update via set $1( + a separate $1 to DSP).

**Comment by viniciusfersil123** [comment]
Fixed in 18/11/2025

**Comment by viniciusfersil123** [comment]
Fixed in 18/11/2025

**Comment by juliesemoroz** [comment]
Hi,

Thanks a lot for the sending.

Is the new program the one on github in code?
I dowloaded it, tested it yesterday and today again to be sure.

The issue 1 is not fixed here when I try it or maybe his is not the new programm you fixed online on code.can you send it to me or let me know about this? thank you

When I load the presets, everthing is fine except the sound. The quality of the sound change ( voice and song of the sea sponges). But volume, attack, relase, duration and swing has to be clicked on every window one by one to have the right sound getting out of the computer.

So it is correctly saved and loaded, all the presets are loaded well visually and physically: but the sound of the audio out doesn't change correctly on the following settings on the 8 window.

volume
attack
relase
duration
swing

I wait for your answer to verify the other issues and try the program properly again.
But from what I saw I didn't see anything else.

thank you for your feedbacks

**Comment by juliesemoroz** [comment]
ok
